apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - active-service.yaml
  - preview-service.yaml

patches:
  - path: rollout-patch.yaml

images:
  - name: ghcr.io/abhinav211/gitops-demo
    newTag: 0856d73e4b94fd2165d6210bfbb43b373b58d094
