apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - active-service.yaml
  - preview-service.yaml

patches:
  - path: rollout-patch.yaml

images:
  - name: ghcr.io/abhinav211/gitops-demo
    newTag: bcf8028e4fc76f397938cf396bef86029546566b
