apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - active-service.yaml
  - preview-service.yaml

patches:
  - path: rollout-patch.yaml

images:
  - name: ghcr.io/abhinav211/gitops-demo
    newTag: 9301cd71f16a4bb562068737a5889b9fc3c2a39c
