apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout.yaml
- active-service.yaml
- preview-service.yaml

images:
- name: ghcr.io/abhinav211/gitops-demo
  newTag: 9301cd71f16a4bb562068737a5889b9fc3c2a39c
