apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: gitops-demo-weighted
  namespace: prod

spec:
  weighted:
    services:
      - name: gitops-demo-stable
        port: 80
        weight: 100

      - name: gitops-demo-canary
        port: 80
        weight: 0
